name-template: 'Version $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## ⬆️ Install or Upgrade
  Follow the [Flow CLI installation guide](https://developers.flow.com/tools/flow-cli/install) for instructions on how to install or upgrade the CLI.

  $CHANGES
categories:
  - title: 💥 Breaking Changes
    label: Breaking Change
  - title: ⭐ Features
    label: Feature
  - title: 🛠 Improvements
    label: Improvement
  - title: 🐞 Bug Fixes
    label: Bugfix
  - title: 📖 Documentation
    label: Documentation
