name: Publish Release

on:
  release:
    types: [published]
jobs:
  homebrew:
    if: "!github.event.release.prerelease"
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: flow-cli
          # https://github.com/mislav/bump-homebrew-formula-action/issues/58
          formula-path: Formula/f/flow-cli.rb
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
